### ISSUE TITLE
encoded_value 타입값을 저장해야 함

### ISSUE THREAD

**Issue by decinc** [decinc/dexassist#5]
기존
value 만 저장

변경
type, value를 동시에 저장

write할 때 encoded_value 추측을 잘못할 수 있는 문제가 있음

ex) longlong -> int로 잘못 추정

**Comment by KimCom903** [comment]
extract_from_annotation_set_item 말고는 encoded_value의 type이 필요한 것이 없나요?? translate_encoded_value가 annotation말고는 안쓰이는 것 같아서요 만약에 type필요한 아이템이 있으면 알려주시겠어요?
