### ISSUE TITLE
opcode에서 method string 등 대신 method를 참조하게 해야 함

### ISSUE THREAD

**Issue by decinc** [decinc/dexassist#9]
현재 method string을 가지고있게 구현되어있는데, method를 참조해야 이름 등 변경시 아이템이 변경됨

**Comment by KimCom903** [comment]
문제를 잘 이해 못한거 같은데 opcode에 접근해야 할떄는 해당 method를 먼저 접근해야 opcode를 접근 가능한거 아닌가요?? method를 참조해야 한다고 하셨는데 method안에 이미 opcode들이 들어 있는거 아닌가요??

**Comment by decinc** [comment]
현재)
manager.get_method 시 메소드 이름 리턴
변경)
manager.get_method 시 메소드 클래스 리턴

이 변경으로 코드 파싱은 메소드 먼저 파싱 다 하고나서 하면 될거같아요

**Comment by decinc** [comment]
메소드가 필요한 이유는 메소드 이름변경 등에 대응하기 위해서입니다
